cloudmesh:
  clouds:
    aws:
      credentials:
        EC2_ACCESS_KEY: 'ACCESS KEY'
        EC2_SECRET_KEY: 'SECRET KEY'
      default:
        image: 'IMAGE ID'
        size: 'SIZE ID'
        location: 'LOCATION'
